### ISSUE TITLE
Hello about shared_mutex

### ISSUE THREAD

**Issue by cucurbita** [HowardHinnant/HowardHinnant.github.io#2]
Hello Howard, is this shared_mutex standalone version, the most recent? 

Thank you.

**Comment by HowardHinnant** [comment]
Hi.  This is the most recent version I've written.  However it is not the most recent according to the C++ standard.  What here is called `shared_mutex` is in C++14 called `shared_timed_mutex`.  And the `upgrade_` facilities were rejected and are not currently planned for any standard.

**Comment by cucurbita** [comment]
Hello, thank you for your quick answer, for my usage, I see it as a placeholder container where I can add my own  facilities such as queue/loop/event ownerships ; the upgrade container is pretty neat and I like it ; they don't know what they miss 8) cheers!

I was looking at your hash-accu solution too, which is for me-self a current-concern, having used spooky in the past, found a lot of caveats ; but this is another story.

- best.
