### ISSUE TITLE
Extra } in date.html

### ISSUE THREAD

**Issue by RoyBellingan** [HowardHinnant/HowardHinnant.github.io#8]
Hi, just a minor typo but in https://howardhinnant.github.io/date/date.html#range
The function limit(const std::string& msg)
The line constexpr auto ymin = sys_days{year::min()}/January/1}; 
has an extra } after the year::min()
(and also the line before)

Bye

**Comment by HowardHinnant** [comment]
Thanks!

**Comment by HowardHinnant** [comment]
Fixed: https://github.com/HowardHinnant/date/commit/dad52961da156af79c630c38b5e4dadb7ba756b6
